Handbook:
  - About the Workshop
  - Development:
    - Vagrant and VirtualBox
    - Git
  - Production:
    - Deploying with Docker
  - Coding:
    - Clean Design
    - GitHub
  - Made in the Workshop:
    - Dummy
